# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projects.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CWidgetProjects(object):
    def setupUi(self, CWidgetProjects):
        CWidgetProjects.setObjectName("CWidgetProjects")
        CWidgetProjects.resize(1023, 527)
        CWidgetProjects.setStyleSheet("background-color: rgb(17, 149, 189);")
        self.verticalLayout = QtWidgets.QVBoxLayout(CWidgetProjects)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(CWidgetProjects)
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("楷体_GB2312")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        self.frame_burnDownChart = QtWidgets.QFrame(CWidgetProjects)
        self.frame_burnDownChart.setStyleSheet("background-color: rgb(182, 182, 182);\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;")
        self.frame_burnDownChart.setObjectName("frame_burnDownChart")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_burnDownChart)
        self.gridLayout_10.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_11 = QtWidgets.QLabel(self.frame_burnDownChart)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(205, 205, 205);\n"
"border-radius:5px;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_burnDownChart, 1, 4, 1, 1)
        self.frame_workloadProgress = QtWidgets.QFrame(CWidgetProjects)
        self.frame_workloadProgress.setStyleSheet("background-color: rgb(182, 182, 182);")
        self.frame_workloadProgress.setObjectName("frame_workloadProgress")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_workloadProgress)
        self.gridLayout_8.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_workloadProgress)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(205, 205, 205);\n"
"border-radius:5px;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_workloadProgress, 1, 2, 1, 1)
        self.frame_timeProgress = QtWidgets.QFrame(CWidgetProjects)
        self.frame_timeProgress.setStyleSheet("background-color: rgb(182, 182, 182);")
        self.frame_timeProgress.setObjectName("frame_timeProgress")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_timeProgress)
        self.gridLayout_7.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.frame_timeProgress)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(205, 205, 205);\n"
"border-radius:5px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_timeProgress, 1, 1, 1, 1)
        self.frame_ProjectName = QtWidgets.QFrame(CWidgetProjects)
        self.frame_ProjectName.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_ProjectName.setStyleSheet("background-color: rgb(182, 182, 182);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;")
        self.frame_ProjectName.setObjectName("frame_ProjectName")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_ProjectName)
        self.gridLayout_6.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_ProjectName)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(205, 205, 205);\n"
"border-radius:5px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_ProjectName, 1, 0, 1, 1)
        self.frame_sprintCycle = QtWidgets.QFrame(CWidgetProjects)
        self.frame_sprintCycle.setStyleSheet("background-color: rgb(182, 182, 182);")
        self.frame_sprintCycle.setObjectName("frame_sprintCycle")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_sprintCycle)
        self.gridLayout_9.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_9.setHorizontalSpacing(7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_10 = QtWidgets.QLabel(self.frame_sprintCycle)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(205, 205, 205);\n"
"border-radius:5px;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_sprintCycle, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.widget = QtWidgets.QWidget(CWidgetProjects)
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(CWidgetProjects)
        QtCore.QMetaObject.connectSlotsByName(CWidgetProjects)

    def retranslateUi(self, CWidgetProjects):
        _translate = QtCore.QCoreApplication.translate
        CWidgetProjects.setWindowTitle(_translate("CWidgetProjects", "Form"))
        self.label.setText(_translate("CWidgetProjects", "project browse"))
        self.label_11.setText(_translate("CWidgetProjects", "burndown"))
        self.label_9.setText(_translate("CWidgetProjects", "workload progress"))
        self.label_8.setText(_translate("CWidgetProjects", "time progress"))
        self.label_7.setText(_translate("CWidgetProjects", "project name"))
        self.label_10.setText(_translate("CWidgetProjects", "sprint cycle"))

import ks24_03_rc
